#!/bin/bash


echo "Archon installer"

PYTHON="$(which python3)"
PIP="$(which pip3)"
APPCONFIG="config/app.yaml"
SAPPCONFIG="config/sample.app.yaml"
APICONFIG="config/api.yaml"
SAPICONFIG="config/sample.api.yaml"
SMTPCONFIG="config/smtp.yaml"
SSMTPCONFIG="config/sample.smtp.yaml"
SITESDIR="storage/sites"
DEVICESDIR="storage/devices"
RESOURCESDIR="storage/resources"
LOGSDIR="storage/logs"
ARCHONDIR="/opt/archon-server"

cd $ARCHONDIR

if [[ ! -x "$PYTHON" ]];
then
    echo  "Python 3 is required, exiting..."
    exit 1
fi

VERSIONRAW="$($PYTHON -V)"
EMPT=""
CLEAN="${VERSIONRAW/Python /$EMPT}"
NUM="${CLEAN//./$EMPT}"

echo $NUM

if [[ "$NUM" -lt "3100" ]];
then
    echo "Python 3.10.0 or newer is required"
    exit 1
fi


if [[ ! -x "$PIP" ]];
then
    echo  "PIP 3 is required, exiting..."
    exit 1
fi

if [[ -x "$PYTHON" ]] & [[ -x "$PIP" ]];
then
    pip3 install pymongo
    pip3 install pyyaml
    pip3 install pyopenssl
    pip3 install pyIsEmail
    pip3 install psutil
    pip3 install websocket
    pip3 install websocket-client
    pip3 install dnspython
    pip3 install python-slugify
    pip3 install asyncssh
    pip3 install nest_asyncio
    pip3 install requests
    pip3 install uvicorn
    pip3 install fastapi
    pip3 install mysql-connector-python
    pip3 install colorama
    pip3 install jinja2
    pip3 install pytz

    if [[ ! -d $SITESDIR ]];
    then
        mkdir -p $SITESDIR
        echo "Created directory $SITESDIR"
    else
        echo "Directory $SITESDIR exists"
    fi

    if [[ ! -d $DEVICESDIR ]];
    then
        mkdir -p $DEVICESDIR
        echo "Created directory $DEVICESDIR"
    else
        echo "Directory $DEVICESDIR exists"
    fi

    if [[ ! -d $RESOURCESDIR ]];
    then
        mkdir -p $RESOURCESDIR
        echo "Created directory $RESOURCESDIR"
    else
        echo "Directory $RESOURCESDIR exists"
    fi

    if [[ ! -d $LOGSDIR ]];
    then
        mkdir -p $LOGSDIR
        echo "Created directory $LOGSDIR"
    else
        echo "Directory $LOGSDIR exists"
    fi

    if [[ ! -f $APPCONFIG ]];
    then
        cp $SAPPCONFIG $APPCONFIG
        echo "Created file $APPCONFIG"
    else
        echo "File $APPCONFIG exists"
    fi

    if [[ ! -f $APICONFIG ]];
    then
        cp $SAPICONFIG $APICONFIG
        echo "Created file $APICONFIG"
    else
        echo "File $APICONFIG exists"
    fi

    if [[ ! -f $SMTPCONFIG ]];
    then
        cp $SSMTPCONFIG $SMTPCONFIG
        echo "Created file $SMTPCONFIG"
    else
        echo "File $SMTPCONFIG exists"
    fi

    ln -s arc /usr/bin/arc
    chmod +x arc server
fi
