#!/bin/bash

PYTHON="$(which python3)"
export PATH="$PATH:."
clear

if [[ -x "$PYTHON" ]];
then
    uvicorn archon-http:webapp --proxy-headers --reload --port 7007
else
    echo  "Python 3 is required, exiting..."
fi
